pubs-db:
  uri: "jdbc:sqlserver://127.0.0.1:1433;databaseName=pubs;encrypt=true;trustServerCertificate=true;"
  user: "sa"
  password: "password"

redis:
  hostname: "127.0.0.1"
  port: 6379
  password: "password"